repository: QweJay/dnspod-shell
repository_url: https://github.com/qwejay

timezone: Asia/Shanghai
lang: zh_CN

title: 导航 - QWENAS
alias_en: QWENAS
alias_cn: 导航 - QWENAS
description: A Navigation Website
keywords: 导航, QWEJAY
url: https://i.qwejay.cn
established_at: "2021-04-10T00:00+08:00"

author: QwejayHuang
author_url: https://i.qwejay.cn/
organization: QWE
organization_url: https://i.qwejay.cn/
contact: contact[at]i.qwejay[dot]cn

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
